using System.Security.Cryptography;
using System.Text;

namespace NdsForge.Corpus;

/// <summary>Reduces private logs to reviewable hash-bound expectations safe to commit without cartridge payloads.</summary>
internal static class CorpusExpectationPublisher
{
    /// <summary>Publishes one expectation per distinct ROM plus a stable index consumed by opt-in tests.</summary>
    /// <param name="libraryPath">Private canonical ROM directory.</param>
    /// <param name="privateOraclePath">Private full-console oracle directory.</param>
    /// <param name="publicPath">Repository directory receiving payload-free JSON.</param>
    /// <param name="catalogPath">Optional refreshed catalog used to resolve renamed files by content hash.</param>
    public static async Task PublishAsync(
        string libraryPath,
        string privateOraclePath,
        string publicPath,
        string? catalogPath = null)
    {
        string library = Path.GetFullPath(libraryPath);
        string privateOracle = Path.GetFullPath(privateOraclePath);
        string output = Path.GetFullPath(publicPath);
        Directory.CreateDirectory(output);
        string[] oracleFiles = Directory.GetFiles(privateOracle, "*.json", SearchOption.TopDirectoryOnly);
        Dictionary<string, CorpusRom>? catalogRoms = catalogPath is null
            ? null
            : (await CorpusJsonFiles.ReadAsync(catalogPath, CorpusJsonContext.Default.CorpusCatalog).ConfigureAwait(false))
                .Roms.ToDictionary(static rom => rom.Sha256, StringComparer.OrdinalIgnoreCase);
        var entries = new List<CorpusExpectationIndexEntry>(oracleFiles.Length);
        string? ndstoolHash = null;
        foreach (string oracleFile in oracleFiles.Order(StringComparer.Ordinal))
        {
            CorpusOracle oracle = await CorpusJsonFiles.ReadAsync(
                oracleFile,
                CorpusJsonContext.Default.CorpusOracle).ConfigureAwait(false);
            ndstoolHash ??= oracle.NdstoolSha256;
            if (!StringComparer.OrdinalIgnoreCase.Equals(ndstoolHash, oracle.NdstoolSha256))
            {
                throw new InvalidDataException("Private oracle files were generated by different ndstool executables.");
            }

            CorpusRom rom = catalogRoms?.GetValueOrDefault(oracle.Rom.Sha256) ?? oracle.Rom;
            string romPath = Path.Combine(library, rom.FileName);
            await using NdsImage image = await NdsImage.OpenAsync(romPath).ConfigureAwait(false);
            NdsValidationResult validation = image.Validate();
            var expectation = new CorpusExpectation(
                1,
                oracle.NdstoolSha256,
                ToExpectedRom(rom),
                validation.Diagnostics.Select(static diagnostic => new ExpectedDiagnostic(
                    diagnostic.Code,
                    diagnostic.Severity,
                    diagnostic.Region?.Offset,
                    diagnostic.Region?.Length)).ToArray(),
                oracle.Operations.Select(static operation => new ExpectedOperation(
                    operation.Name,
                    operation.ExitCode,
                    HashText(operation.StandardOutput),
                    HashText(operation.StandardError),
                    operation.Artifacts)).ToArray());
            string expectationFile = $"{rom.GameCode}-{rom.Sha256[..12]}.json";
            await CorpusJsonFiles.WriteAsync(
                Path.Combine(output, expectationFile),
                expectation,
                CorpusJsonContext.Default.CorpusExpectation).ConfigureAwait(false);
            entries.Add(new(rom.FileName, rom.Sha256, expectationFile));
        }

        if (ndstoolHash is null)
        {
            throw new InvalidDataException("No private oracle JSON files were found.");
        }

        var index = new CorpusExpectationIndex(
            1,
            ndstoolHash,
            entries.OrderBy(static entry => entry.Name, StringComparer.Ordinal).ToArray());
        await CorpusJsonFiles.WriteAsync(
            Path.Combine(output, "index.json"),
            index,
            CorpusJsonContext.Default.CorpusExpectationIndex).ConfigureAwait(false);
        await Console.Out.WriteLineAsync($"Published {entries.Count} SHA-256-keyed expectation documents.").ConfigureAwait(false);
    }

    /// <summary>Copies only content-derived naming and typed cartridge identity into the public contract.</summary>
    /// <param name="rom">Private catalog row that also contains the discarded import filename.</param>
    /// <returns>Payload-free public identity.</returns>
    private static ExpectedRom ToExpectedRom(CorpusRom rom) => new(
        rom.FileName,
        rom.Length,
        rom.Sha256,
        rom.HeaderTitle,
        rom.GameCode,
        rom.MakerCode,
        rom.Kind,
        rom.Revision,
        rom.Region,
        rom.PreferredLanguage,
        rom.DisplayTitle,
        rom.BannerTitles);

    /// <summary>Hashes UTF-8 console text after normalizing Windows and legacy carriage-return line endings.</summary>
    /// <param name="value">Captured private output omitted from the public repository.</param>
    /// <returns>Uppercase SHA-256 of normalized UTF-8 text.</returns>
    private static string HashText(string value)
    {
        string normalized = value.Replace("\r\n", "\n", StringComparison.Ordinal)
            .Replace('\r', '\n');
        return Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(normalized)));
    }
}
